import Foundation

/// Generates a hysteria2 client YAML config from a `Connection` + `AppSettings`.
///
/// The CN-direct / rest-proxied split is implemented entirely with hysteria's
/// built-in ACL engine: `direct`, `reject` and `default` are reserved outbounds,
/// so we route geoip:cn / geosite:cn to `direct` and let everything else fall
/// through to the proxy (the implicit default outbound).
enum ConfigBuilder {

    static func makeConfig(for connection: Connection, settings: AppSettings) -> String {
        // Power-user escape hatch: use the pasted config verbatim.
        if let raw = connection.rawConfigOverride,
           !raw.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return raw
        }

        var lines: [String] = []
        lines.append("# Generated by HysteriaManager. Do not edit by hand — changes are overwritten.")
        lines.append("server: \(yaml(connection.server.isEmpty ? "\(connection.host):\(connection.port)" : connection.server))")
        lines.append("auth: \(yaml(connection.auth))")

        // Bandwidth
        if connection.upMbps > 0 || connection.downMbps > 0 {
            lines.append("bandwidth:")
            if connection.upMbps > 0   { lines.append("  up: \(connection.upMbps) mbps") }
            if connection.downMbps > 0 { lines.append("  down: \(connection.downMbps) mbps") }
        }

        // TLS
        var tls: [String] = []
        if !connection.sni.isEmpty       { tls.append("  sni: \(yaml(connection.sni))") }
        if connection.insecure           { tls.append("  insecure: true") }
        if !connection.pinSHA256.isEmpty { tls.append("  pinSHA256: \(yaml(connection.pinSHA256))") }
        if !tls.isEmpty {
            lines.append("tls:")
            lines.append(contentsOf: tls)
        }

        // Obfuscation
        if connection.obfsType == .salamander, !connection.obfsPassword.isEmpty {
            lines.append("obfs:")
            lines.append("  type: salamander")
            lines.append("  salamander:")
            lines.append("    password: \(yaml(connection.obfsPassword))")
        }

        // Local listeners
        lines.append("socks5:")
        lines.append("  listen: 127.0.0.1:\(settings.socksPort)")
        lines.append("http:")
        lines.append("  listen: 127.0.0.1:\(settings.httpPort)")

        // Performance toggles
        if connection.fastOpen { lines.append("fastOpen: true") }
        if connection.lazy     { lines.append("lazy: true") }

        // Routing via ACL
        let acl = aclLines(for: connection, settings: settings)
        if !acl.isEmpty {
            lines.append("acl:")
            lines.append("  inline:")
            for rule in acl { lines.append("    - \(rule)") }
            if !settings.geoipPath.isEmpty   { lines.append("  geoip: \(yaml(settings.geoipPath))") }
            if !settings.geositePath.isEmpty { lines.append("  geosite: \(yaml(settings.geositePath))") }
        }

        return lines.joined(separator: "\n") + "\n"
    }

    /// The ACL rule list for the connection's routing mode.
    static func aclLines(for connection: Connection, settings: AppSettings) -> [String] {
        switch connection.routingMode {
        case .global:
            // No rules needed; everything falls through to the default (proxy) outbound.
            // We still honor any user reject/extra rules.
            return connection.extraACL
        case .direct:
            // Send everything direct — proxy stays connected but unused.
            return connection.extraACL + ["direct(all)"]
        case .ruleBased:
            var rules: [String] = []
            // Private / LAN ranges never go through the tunnel.
            rules.append("direct(geoip:private)")
            // Mainland China stays direct.
            rules.append("direct(geoip:cn)")
            rules.append("direct(geosite:cn)")
            rules.append("direct(geosite:geolocation-cn)")
            // Any user-supplied rules (e.g. reject ads, force a domain through proxy).
            rules.append(contentsOf: connection.extraACL)
            // Catch-all: send the rest through the proxy.
            rules.append("default(all)")
            return rules
        }
    }

    // MARK: YAML scalar escaping

    /// Quote a scalar when it could otherwise be misparsed by YAML.
    private static func yaml(_ value: String) -> String {
        if value.isEmpty { return "\"\"" }
        let needsQuoting = value.contains(where: { ":#{}[],&*!|>'\"%@`".contains($0) })
            || value.first == " " || value.last == " "
            || ["true", "false", "yes", "no", "null", "~"].contains(value.lowercased())
        guard needsQuoting else { return value }
        let escaped = value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
        return "\"\(escaped)\""
    }
}
